
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author user
 */
public class home extends javax.swing.JFrame {

    /**
     * Creates new form home
     */
    public home() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        hb_goa = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        hb_lakh = new javax.swing.JButton();
        jTextField4 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        hb_dineout = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        offsites = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        weekend = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextField1.setFont(new java.awt.Font("Algerian", 1, 24)); // NOI18N
        jTextField1.setForeground(new java.awt.Color(255, 0, 0));
        jTextField1.setText("                      Welcome to fly with sea");
        jTextField1.setCaretColor(new java.awt.Color(102, 255, 255));
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(749, 0, 575, 76));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 89, 1919, 10));

        jButton1.setFont(new java.awt.Font("Algerian", 1, 12)); // NOI18N
        jButton1.setText("Book Now");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1781, 180, -1, 37));

        jButton2.setFont(new java.awt.Font("Algerian", 1, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(153, 0, 0));
        jButton2.setText("LogOut");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1802, 984, 105, 38));

        jButton3.setFont(new java.awt.Font("Algerian", 1, 14)); // NOI18N
        jButton3.setForeground(new java.awt.Color(153, 0, 0));
        jButton3.setText("Close");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1840, 0, -1, -1));

        jTextField2.setFont(new java.awt.Font("Algerian", 1, 14)); // NOI18N
        jTextField2.setForeground(new java.awt.Color(204, 0, 51));
        jTextField2.setText("Customer Support: 8276983936");
        getContentPane().add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1664, 51, -1, -1));

        jTextField3.setFont(new java.awt.Font("Algerian", 0, 24)); // NOI18N
        jTextField3.setForeground(new java.awt.Color(204, 0, 204));
        jTextField3.setText("                              Our Top Cruise Destination");
        jTextField3.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jTextField3.setEnabled(false);
        jTextField3.setRequestFocusEnabled(false);
        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(589, 224, 675, -1));

        hb_goa.setFont(new java.awt.Font("Algerian", 1, 14)); // NOI18N
        hb_goa.setForeground(new java.awt.Color(0, 51, 255));
        hb_goa.setText("Explore more");
        hb_goa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hb_goaActionPerformed(evt);
            }
        });
        getContentPane().add(hb_goa, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 390, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/goa3.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 290, -1, 220));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/asia.jpg"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1060, 280, -1, 209));

        hb_lakh.setFont(new java.awt.Font("Algerian", 1, 14)); // NOI18N
        hb_lakh.setForeground(new java.awt.Color(0, 51, 255));
        hb_lakh.setText("Explore more");
        hb_lakh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hb_lakhActionPerformed(evt);
            }
        });
        getContentPane().add(hb_lakh, new org.netbeans.lib.awtextra.AbsoluteConstraints(1370, 410, -1, -1));

        jTextField4.setFont(new java.awt.Font("Algerian", 1, 24)); // NOI18N
        jTextField4.setForeground(new java.awt.Color(255, 0, 0));
        jTextField4.setText("SEACATION ");
        jTextField4.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jTextField4.setEnabled(false);
        jTextField4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField4ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 590, 210, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/2ndCruise.jpg"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 650, -1, 223));
        getContentPane().add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 967, 1919, 10));

        hb_dineout.setFont(new java.awt.Font("Algerian", 1, 14)); // NOI18N
        hb_dineout.setForeground(new java.awt.Color(0, 51, 255));
        hb_dineout.setText(" Dine Out with Families and Friends");
        hb_dineout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hb_dineoutActionPerformed(evt);
            }
        });
        getContentPane().add(hb_dineout, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 860, -1, 50));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/View more.jpg"))); // NOI18N
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 660, 390, 194));

        offsites.setFont(new java.awt.Font("Algerian", 1, 14)); // NOI18N
        offsites.setForeground(new java.awt.Color(0, 51, 255));
        offsites.setText("Offsites and Events");
        offsites.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                offsitesActionPerformed(evt);
            }
        });
        getContentPane().add(offsites, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 880, 210, 40));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/weekhome.jpg"))); // NOI18N
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(1360, 660, 370, 210));

        weekend.setFont(new java.awt.Font("Algerian", 1, 14)); // NOI18N
        weekend.setForeground(new java.awt.Color(0, 51, 255));
        weekend.setText("Weekend Cruise experience");
        weekend.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        weekend.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                weekendActionPerformed(evt);
            }
        });
        getContentPane().add(weekend, new org.netbeans.lib.awtextra.AbsoluteConstraints(1420, 890, 270, 40));
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 790, -1, -1));

        jLabel6.setFont(new java.awt.Font("Perpetua Titling MT", 1, 24)); // NOI18N
        jLabel6.setText("LAKSHADWEEP");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(1370, 300, -1, 30));

        jLabel8.setFont(new java.awt.Font("Perpetua Titling MT", 1, 24)); // NOI18N
        jLabel8.setText("LAKSHADWEEP");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(1370, 300, -1, 30));

        jLabel9.setFont(new java.awt.Font("Perpetua Titling MT", 1, 24)); // NOI18N
        jLabel9.setText("LAKSHADWEEP");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(1370, 300, -1, 30));

        jLabel10.setFont(new java.awt.Font("Perpetua Titling MT", 1, 24)); // NOI18N
        jLabel10.setText("Goa");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 300, -1, -1));

        jLabel11.setFont(new java.awt.Font("Rockwell", 0, 24)); // NOI18N
        jLabel11.setText("Explore The Unexplored CORAL PARADISE");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(1370, 340, -1, -1));

        jLabel12.setFont(new java.awt.Font("Rockwell", 0, 24)); // NOI18N
        jLabel12.setText("Experience The CHARM");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 340, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        int a = JOptionPane.showConfirmDialog(null, "Do you really want to logout", "select", JOptionPane.YES_NO_OPTION);
        if(a == 0){
            setVisible(false);
            new login().setVisible(true);
        }
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
         int a = JOptionPane.showConfirmDialog(null, "Do you really want to close application", "select", JOptionPane.YES_NO_OPTION);
        if(a == 0){
            System.exit(0);
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
//        setVisible(false);
//        new booknow().setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3ActionPerformed

    private void hb_goaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hb_goaActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        new Goa().setVisible(true);
        
    }//GEN-LAST:event_hb_goaActionPerformed

    private void hb_lakhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hb_lakhActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        new lakh().setVisible(true);
        
    }//GEN-LAST:event_hb_lakhActionPerformed

    private void jTextField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField4ActionPerformed

    private void hb_dineoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hb_dineoutActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        new dineout().setVisible(true);
    }//GEN-LAST:event_hb_dineoutActionPerformed

    private void offsitesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_offsitesActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        new offsites().setVisible(true);
    }//GEN-LAST:event_offsitesActionPerformed

    private void weekendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_weekendActionPerformed

        // TODO add your handling code here:
        setVisible(false);
        new weekend().setVisible(true);
    }//GEN-LAST:event_weekendActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton hb_dineout;
    private javax.swing.JButton hb_goa;
    private javax.swing.JButton hb_lakh;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JButton offsites;
    private javax.swing.JButton weekend;
    // End of variables declaration//GEN-END:variables
}
