
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author user
 */
public class home extends javax.swing.JFrame {

    /**
     * Creates new form home
     */
    public home(String email) {
        initComponents();
        jLabel22.setText(email);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator1 = new javax.swing.JSeparator();
        b_book = new javax.swing.JButton();
        b_logout = new javax.swing.JButton();
        b_close = new javax.swing.JButton();
        jTextField2 = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        b_goa = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        b_lakh = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        b_dineout = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        b_offsites = new javax.swing.JButton();
        b_weekend = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 89, 1919, 10));

        b_book.setFont(new java.awt.Font("Algerian", 1, 12)); // NOI18N
        b_book.setText("Book Now");
        b_book.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_bookActionPerformed(evt);
            }
        });
        getContentPane().add(b_book, new org.netbeans.lib.awtextra.AbsoluteConstraints(1740, 160, -1, 37));

        b_logout.setFont(new java.awt.Font("Algerian", 1, 14)); // NOI18N
        b_logout.setForeground(new java.awt.Color(153, 0, 0));
        b_logout.setText("LogOut");
        b_logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_logoutActionPerformed(evt);
            }
        });
        getContentPane().add(b_logout, new org.netbeans.lib.awtextra.AbsoluteConstraints(1780, 980, 105, 38));

        b_close.setFont(new java.awt.Font("Algerian", 1, 14)); // NOI18N
        b_close.setForeground(new java.awt.Color(153, 0, 0));
        b_close.setText("Close");
        b_close.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_closeActionPerformed(evt);
            }
        });
        getContentPane().add(b_close, new org.netbeans.lib.awtextra.AbsoluteConstraints(1810, 10, -1, -1));

        jTextField2.setFont(new java.awt.Font("Algerian", 1, 14)); // NOI18N
        jTextField2.setForeground(new java.awt.Color(204, 0, 51));
        jTextField2.setText("Customer Support: 8276983936");
        getContentPane().add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1630, 50, -1, -1));

        jLabel22.setText("jLabel22");
        getContentPane().add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(1600, 120, -1, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel8.setText("User");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(1530, 110, -1, -1));

        b_goa.setFont(new java.awt.Font("Algerian", 1, 14)); // NOI18N
        b_goa.setForeground(new java.awt.Color(0, 51, 255));
        b_goa.setText("Explore more");
        b_goa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_goaActionPerformed(evt);
            }
        });
        getContentPane().add(b_goa, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 540, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/goa3.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 440, 340, 180));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/asia.jpg"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 440, -1, 180));

        b_lakh.setFont(new java.awt.Font("Algerian", 1, 14)); // NOI18N
        b_lakh.setForeground(new java.awt.Color(0, 51, 255));
        b_lakh.setText("Explore more");
        b_lakh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_lakhActionPerformed(evt);
            }
        });
        getContentPane().add(b_lakh, new org.netbeans.lib.awtextra.AbsoluteConstraints(1400, 530, -1, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/2ndCruise.jpg"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 680, -1, 223));
        getContentPane().add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 967, 1919, 10));

        b_dineout.setFont(new java.awt.Font("Algerian", 1, 14)); // NOI18N
        b_dineout.setForeground(new java.awt.Color(0, 51, 255));
        b_dineout.setText("Explore more");
        b_dineout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_dineoutActionPerformed(evt);
            }
        });
        getContentPane().add(b_dineout, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 930, -1, 30));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/View more.jpg"))); // NOI18N
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 700, -1, 180));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/weekhome.jpg"))); // NOI18N
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(1260, 700, 350, 190));

        b_offsites.setFont(new java.awt.Font("Algerian", 1, 14)); // NOI18N
        b_offsites.setForeground(new java.awt.Color(0, 51, 255));
        b_offsites.setText("explore more");
        b_offsites.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_offsitesActionPerformed(evt);
            }
        });
        getContentPane().add(b_offsites, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 930, 150, 30));

        b_weekend.setFont(new java.awt.Font("Algerian", 1, 14)); // NOI18N
        b_weekend.setForeground(new java.awt.Color(0, 51, 255));
        b_weekend.setText("explore more");
        b_weekend.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        b_weekend.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_weekendActionPerformed(evt);
            }
        });
        getContentPane().add(b_weekend, new org.netbeans.lib.awtextra.AbsoluteConstraints(1360, 930, 160, 30));
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 790, -1, -1));

        jLabel6.setFont(new java.awt.Font("Perpetua Titling MT", 1, 24)); // NOI18N
        jLabel6.setText("LAKSHADWEEP");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(1390, 450, -1, 30));

        jLabel9.setFont(new java.awt.Font("Perpetua Titling MT", 1, 24)); // NOI18N
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(1400, 420, -1, 30));

        jLabel10.setBackground(new java.awt.Color(255, 255, 255));
        jLabel10.setFont(new java.awt.Font("Algerian", 1, 24)); // NOI18N
        jLabel10.setText("  SEACATION ");
        jLabel10.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 630, 170, 50));

        jLabel11.setFont(new java.awt.Font("Rockwell", 0, 24)); // NOI18N
        jLabel11.setText("Explore The Unexplored CORAL PARADISE");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(1390, 490, -1, -1));

        jLabel12.setFont(new java.awt.Font("Rockwell", 0, 24)); // NOI18N
        jLabel12.setText("Dine out with Friends &Families");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 890, -1, -1));

        jLabel13.setFont(new java.awt.Font("Rockwell", 0, 24)); // NOI18N
        jLabel13.setText("Offsites & Events");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 900, -1, -1));

        jLabel14.setFont(new java.awt.Font("Rockwell", 0, 24)); // NOI18N
        jLabel14.setText("Weekend Cruise Experience");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(1270, 900, -1, -1));

        jLabel15.setFont(new java.awt.Font("Rockwell", 0, 24)); // NOI18N
        jLabel15.setText("Experience The CHARM");
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 500, -1, -1));

        jLabel17.setFont(new java.awt.Font("Perpetua Titling MT", 1, 24)); // NOI18N
        jLabel17.setText("Goa");
        getContentPane().add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 450, -1, -1));

        jLabel18.setFont(new java.awt.Font("Algerian", 1, 24)); // NOI18N
        jLabel18.setText("  Our Top Cruise Destination");
        jLabel18.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 380, 390, 50));

        jLabel19.setFont(new java.awt.Font("Algerian", 1, 24)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 0, 0));
        jLabel19.setText("Make your moments magical with magical moments");
        getContentPane().add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 50, -1, -1));

        jLabel20.setFont(new java.awt.Font("Algerian", 1, 24)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 0, 0));
        jLabel20.setText("welcome to magic moments...");
        getContentPane().add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 10, -1, -1));

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/h_royalty_full.jpg"))); // NOI18N
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1900, -1));

        jLabel21.setFont(new java.awt.Font("Algerian", 1, 24)); // NOI18N
        jLabel21.setText("  Our Top Cruise Destination");
        jLabel21.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 350, 390, 50));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void b_logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_logoutActionPerformed
        // TODO add your handling code here:
        int a = JOptionPane.showConfirmDialog(null, "Do you really want to logout", "select", JOptionPane.YES_NO_OPTION);
        if(a == 0){
            setVisible(false);
            new login().setVisible(true);
        }
        
    }//GEN-LAST:event_b_logoutActionPerformed

    private void b_closeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_closeActionPerformed
        // TODO add your handling code here:
         int a = JOptionPane.showConfirmDialog(null, "Do you really want to close application", "select", JOptionPane.YES_NO_OPTION);
        if(a == 0){
            System.exit(0);
        }
    }//GEN-LAST:event_b_closeActionPerformed

    private void b_bookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_bookActionPerformed
//        setVisible(false);
        new Booknow(jLabel22.getText()).setVisible(true);      // TODO add your handling code here:
//        setVisible(false);
//        new booknow().setVisible(true);
    }//GEN-LAST:event_b_bookActionPerformed

    private void b_goaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_goaActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        new Goa().setVisible(true);
        
    }//GEN-LAST:event_b_goaActionPerformed

    private void b_lakhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_lakhActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        new lakh().setVisible(true);
        
    }//GEN-LAST:event_b_lakhActionPerformed

    private void b_dineoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_dineoutActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        new friends().setVisible(true);
    }//GEN-LAST:event_b_dineoutActionPerformed

    private void b_offsitesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_offsitesActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        new events().setVisible(true);
    }//GEN-LAST:event_b_offsitesActionPerformed

    private void b_weekendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_weekendActionPerformed

        // TODO add your handling code here:
        setVisible(false);
        new weekend().setVisible(true);
    }//GEN-LAST:event_b_weekendActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new home(null).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton b_book;
    private javax.swing.JButton b_close;
    private javax.swing.JButton b_dineout;
    private javax.swing.JButton b_goa;
    private javax.swing.JButton b_lakh;
    private javax.swing.JButton b_logout;
    private javax.swing.JButton b_offsites;
    private javax.swing.JButton b_weekend;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables
}
